### ISSUE TITLE
第二次讨论：第一阶段细节讨论

### ISSUE THREAD

**Issue by r-zh** [WebLogicVulnerability/E-C#5]
1.代码模拟放入购物车：
（通过图建立访问不妥，选择用python解析HTTP请求，并获得Response，并提取出对应的URL进行解析，结合图进一步发送HTTP请求）
结合图和实际进行编辑

2.代码模拟用户登录
参照1中的代码内容，放入对应的HTTP请求，查找并修改错误。
经过一番研究思考，我们发现需要从根源上修改思路，以生成图为中心，放入我们需要的数据，再进行http请求访问
时间很晚了，明天继续做：
graph.dot正确写入参数；完成图中显示参数的功能
下一步 模拟登录

3.URL动态生成问题

**Comment by r-zh** [comment]
第一部分：
通过图中的URL和浏览器访问的URL对比，找出每次会话变化的部分，例如：sessionID，后来发现通过设置cookie就能将其他变化的部分做出适应HTTP请求的更改；
通过cookielib来查找每次会话产生的sessionID
现在实现的是用字符串长度截取。
后来发现通过urllib2（其中已经包含了sessionID），只要将链接作为参数，利用urllib和urllib2就能想服务器发送http请求，并获得response，第一部分模拟放入购物车成功。

第一阶段完成，成功利用代码自动添加物品到购物车

**Comment by r-zh** [comment]
第二部分：
当我们再次使用构造的方法实现登录时，我们发现，上一次的http参数的解析是特定的URL（我们默认为特定位置为参数的位置），但是发现改了其他的HTTP请求例如登录的，参数位置发生了改变，也就是说，我们需要在生成图的时候将url和参数放入文件当中，这是我们的首要问题。
为解决这一问题，需要先建立一个python文件作为burpsuite的接口插件，实现图中包含http请求参数内容的功能，另外，需要在项目中实现读取图中内容（即设置好的URL和Param），完成接下来发送HTTP请求的目的。
进一步了解之后，生成图之前，插件的功能是实现trace.txt文件，然后再生成图，经过验证之后，我们发现，不同的post页面参数的形式也是不一样的，例如大多数情况下是这样的：

``` java
startCityId=144&destCity=JingXuan&guessIndex=0
```

而我们遇到的部分却是:

``` java
------WebKitFormBoundaryvIYQr4iPJ5CdALiy
Content-Disposition: form-data; name="email"

tonyzhou@live.cn
------WebKitFormBoundaryvIYQr4iPJ5CdALiy
Content-Disposition: form-data; name="password"

619845
------WebKitFormBoundaryvIYQr4iPJ5CdALiy--
```

无论参数格式如何变化，burpsuite都能够解析
![default](https://cloud.githubusercontent.com/assets/7058710/7430334/59c86792-f044-11e4-879e-d9b1c28e9037.jpg)

因此，我们决定利用burpsuite提供的接口方法，来帮我们完成这一步
我们发现trace文件中有很多多余的部分：
![qq 20150501212618](https://cloud.githubusercontent.com/assets/7058710/7430659/bdde3154-f048-11e4-8be7-f1cd88fb8ac4.jpg)
为使我们的工作尽量地简洁，系统更加轻量，我们决定采用正则表达式进行处理，只留下重要部分的内容

**Comment by r-zh** [comment]
在这一阶段，我们遇到了关于URL重定向以及URL动态生成的问题（这一条URL里的参数，和上一个会话相关），浩鹏感到超乎想象的压力，所以决定，出去走走
需要解决的问题如下：
1，跟随post返回的重定向(已解决)
2，解决动态生成Url的问题：
（1）需要修改的参数：currentSession,currentDispatch,Session,Dispatch,auth
解决方法：从前面的response中获取到这些参数，作为新的post参数传递
post方法中的CURRENT_SESSION是上一个请求中url中的session
                     SESSION是上一个响应返回内容中的session（推测可能与登陆按钮有关）
获得了所需参数,但是Post之后返回dispatch error
修改参数之后的信息可以post到paypal的支付页面但是登陆存在问题，不再继续登陆。（因为在paypal上可以见到修改后的金额，登陆后继续支付的金额就是该金额，所以到此已经能证明存在logic漏洞）

**Comment by hp-yang** [comment]
第三部分：
自动根据图访问url功能的开发暂时告一段落，下一步进行读取配置文件中的参数并进行相应修改，并作为新的参数进行post以验证是否有逻辑漏洞
